# Generated by Django 5.0.4 on 2024-04-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cep',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
