# Generated by Django 5.0.4 on 2024-04-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gel', '0006_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
